[pytest]
minversion = 8.4
DJANGO_SETTINGS_MODULE = config.settings
env =
  DJANGO_TEST=True

testpaths =
  api/tests
  core/tests
python_files = test_*.py

addopts =
    -s
    -v
    -rsxX
    --strict-markers
    --tb=short
    --disable-pytest-warnings
    --reuse-db

xfail_strict = true
