SIMILARITY_THRESH_VERY_LOOSE = 0.20
SIMILARITY_THRESH_LOOSE = 0.30
SIMILARITY_THRESH_MODERATE = 0.50
SIMILARITY_THRESH_STRICT = 0.75
SIMILARITY_THRESH_VERY_STRICT = 0.95

EMAIL_SEARCH_MIN_LENGTH = 3
USER_SEARCH_MIN_LENGTH = 3
