CANONICAL = (
  {
    'country_code': 'CI',
    'coordinate': '+0519−00402',
    'code': 'Africa/Abidjan',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'GH',
    'coordinate': '+0533−00013',
    'code': 'Africa/Accra',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'DZ',
    'coordinate': '+3647+00303',
    'code': 'Africa/Algiers',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+01:00',
  },
  {
    'country_code': 'GW',
    'coordinate': '+1151−01535',
    'code': 'Africa/Bissau',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'EG',
    'coordinate': '+3003+03115',
    'code': 'Africa/Cairo',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'MA',
    'coordinate': '+3339−00735',
    'code': 'Africa/Casablanca',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'ES',
    'coordinate': '+3553−00519',
    'code': 'Africa/Ceuta',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'EH',
    'coordinate': '+2709−01312',
    'code': 'Africa/El_Aaiun',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'ZA',
    'coordinate': '−2615+02800',
    'code': 'Africa/Johannesburg',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+02:00',
    'active': True,
  },
  {
    'country_code': 'SS',
    'coordinate': '+0451+03137',
    'code': 'Africa/Juba',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'SD',
    'coordinate': '+1536+03232',
    'code': 'Africa/Khartoum',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'NG',
    'coordinate': '+0627+00324',
    'code': 'Africa/Lagos',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+01:00',
  },
  {
    'country_code': 'MZ',
    'coordinate': '−2558+03235',
    'code': 'Africa/Maputo',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'LR',
    'coordinate': '+0618−01047',
    'code': 'Africa/Monrovia',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'KE',
    'coordinate': '−0117+03649',
    'code': 'Africa/Nairobi',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'TD',
    'coordinate': '+1207+01503',
    'code': 'Africa/Ndjamena',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+01:00',
  },
  {
    'country_code': 'ST',
    'coordinate': '+0020+00644',
    'code': 'Africa/Sao_Tome',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'LY',
    'coordinate': '+3254+01311',
    'code': 'Africa/Tripoli',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'TN',
    'coordinate': '+3648+01011',
    'code': 'Africa/Tunis',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+01:00',
  },
  {
    'country_code': 'nan',
    'coordinate': '−2234+01706',
    'code': 'Africa/Windhoek',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+515248−1763929',
    'code': 'America/Adak',
    'status': 'Canonical',
    'utc_offset': '−10:00',
    'utc_dst_offset': '−09:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+611305−1495401',
    'code': 'America/Anchorage',
    'status': 'Canonical',
    'utc_offset': '−09:00',
    'utc_dst_offset': '−08:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−0712−04812',
    'code': 'America/Araguaina',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−3436−05827',
    'code': 'America/Argentina/Buenos_Aires',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−2828−06547',
    'code': 'America/Argentina/Catamarca',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−3124−06411',
    'code': 'America/Argentina/Cordoba',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−2411−06518',
    'code': 'America/Argentina/Jujuy',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−2926−06651',
    'code': 'America/Argentina/La_Rioja',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−3253−06849',
    'code': 'America/Argentina/Mendoza',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−5138−06913',
    'code': 'America/Argentina/Rio_Gallegos',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−2447−06525',
    'code': 'America/Argentina/Salta',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−3132−06831',
    'code': 'America/Argentina/San_Juan',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−3319−06621',
    'code': 'America/Argentina/San_Luis',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−2649−06513',
    'code': 'America/Argentina/Tucuman',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AR',
    'coordinate': '−5448−06818',
    'code': 'America/Argentina/Ushuaia',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'PY',
    'coordinate': '−2516−05740',
    'code': 'America/Asuncion',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+484531−0913718',
    'code': 'America/Atikokan',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−1259−03831',
    'code': 'America/Bahia',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'MX',
    'coordinate': '+2048−10515',
    'code': 'America/Bahia_Banderas',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'BB',
    'coordinate': '+1306−05937',
    'code': 'America/Barbados',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−0127−04829',
    'code': 'America/Belem',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'BZ',
    'coordinate': '+1730−08812',
    'code': 'America/Belize',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+5125−05707',
    'code': 'America/Blanc-Sablon',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '+0249−06040',
    'code': 'America/Boa_Vista',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'CO',
    'coordinate': '+0436−07405',
    'code': 'America/Bogota',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+433649−1161209',
    'code': 'America/Boise',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+690650−1050310',
    'code': 'America/Cambridge_Bay',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−2027−05437',
    'code': 'America/Campo_Grande',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'MX',
    'coordinate': '+2105−08646',
    'code': 'America/Cancun',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'VE',
    'coordinate': '+1030−06656',
    'code': 'America/Caracas',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'GF',
    'coordinate': '+0456−05220',
    'code': 'America/Cayenne',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+415100−0873900',
    'code': 'America/Chicago',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
    'active': True,
  },
  {
    'country_code': 'MX',
    'coordinate': '+2838−10605',
    'code': 'America/Chihuahua',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'CR',
    'coordinate': '+0956−08405',
    'code': 'America/Costa_Rica',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+4906−11631',
    'code': 'America/Creston',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−07:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−1535−05605',
    'code': 'America/Cuiaba',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'CW',
    'coordinate': '+1211−06900',
    'code': 'America/Curacao',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'GL',
    'coordinate': '+7646−01840',
    'code': 'America/Danmarkshavn',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+6404−13925',
    'code': 'America/Dawson',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−07:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+5946−12014',
    'code': 'America/Dawson_Creek',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−07:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+394421−1045903',
    'code': 'America/Denver',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−06:00',
    'active': True,
  },
  {
    'country_code': 'US',
    'coordinate': '+421953−0830245',
    'code': 'America/Detroit',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+5333−11328',
    'code': 'America/Edmonton',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−0640−06952',
    'code': 'America/Eirunepe',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'SV',
    'coordinate': '+1342−08912',
    'code': 'America/El_Salvador',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+5848−12242',
    'code': 'America/Fort_Nelson',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−07:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−0343−03830',
    'code': 'America/Fortaleza',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+4612−05957',
    'code': 'America/Glace_Bay',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+5320−06025',
    'code': 'America/Goose_Bay',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'TC',
    'coordinate': '+2128−07108',
    'code': 'America/Grand_Turk',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'GT',
    'coordinate': '+1438−09031',
    'code': 'America/Guatemala',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'EC',
    'coordinate': '−0210−07950',
    'code': 'America/Guayaquil',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'GY',
    'coordinate': '+0648−05810',
    'code': 'America/Guyana',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+4439−06336',
    'code': 'America/Halifax',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'CU',
    'coordinate': '+2308−08222',
    'code': 'America/Havana',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'MX',
    'coordinate': '+2904−11058',
    'code': 'America/Hermosillo',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−07:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+394606−0860929',
    'code': 'America/Indiana/Indianapolis',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+411745−0863730',
    'code': 'America/Indiana/Knox',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+382232−0862041',
    'code': 'America/Indiana/Marengo',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+382931−0871643',
    'code': 'America/Indiana/Petersburg',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+375711−0864541',
    'code': 'America/Indiana/Tell_City',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+384452−0850402',
    'code': 'America/Indiana/Vevay',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+384038−0873143',
    'code': 'America/Indiana/Vincennes',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+410305−0863611',
    'code': 'America/Indiana/Winamac',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+682059−1334300',
    'code': 'America/Inuvik',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+6344−06828',
    'code': 'America/Iqaluit',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'JM',
    'coordinate': '+175805−0764736',
    'code': 'America/Jamaica',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+581807−1342511',
    'code': 'America/Juneau',
    'status': 'Canonical',
    'utc_offset': '−09:00',
    'utc_dst_offset': '−08:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+381515−0854534',
    'code': 'America/Kentucky/Louisville',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+364947−0845057',
    'code': 'America/Kentucky/Monticello',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'BO',
    'coordinate': '−1630−06809',
    'code': 'America/La_Paz',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'PE',
    'coordinate': '−1203−07703',
    'code': 'America/Lima',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+340308−1181434',
    'code': 'America/Los_Angeles',
    'status': 'Canonical',
    'utc_offset': '−08:00',
    'utc_dst_offset': '−07:00',
    'active': True,
  },
  {
    'country_code': 'BR',
    'coordinate': '−0940−03543',
    'code': 'America/Maceio',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'NI',
    'coordinate': '+1209−08617',
    'code': 'America/Managua',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−0308−06001',
    'code': 'America/Manaus',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'MQ',
    'coordinate': '+1436−06105',
    'code': 'America/Martinique',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'MX',
    'coordinate': '+2550−09730',
    'code': 'America/Matamoros',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'MX',
    'coordinate': '+2313−10625',
    'code': 'America/Mazatlan',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+450628−0873651',
    'code': 'America/Menominee',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'MX',
    'coordinate': '+2058−08937',
    'code': 'America/Merida',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+550737−1313435',
    'code': 'America/Metlakatla',
    'status': 'Canonical',
    'utc_offset': '−09:00',
    'utc_dst_offset': '−08:00',
  },
  {
    'country_code': 'MX',
    'coordinate': '+1924−09909',
    'code': 'America/Mexico_City',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
    'active': True,
  },
  {
    'country_code': 'PM',
    'coordinate': '+4703−05620',
    'code': 'America/Miquelon',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−02:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+4606−06447',
    'code': 'America/Moncton',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'MX',
    'coordinate': '+2540−10019',
    'code': 'America/Monterrey',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'UY',
    'coordinate': '−345433−0561245',
    'code': 'America/Montevideo',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'BS',
    'coordinate': '+2505−07721',
    'code': 'America/Nassau',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+404251−0740023',
    'code': 'America/New_York',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
    'active': True,
  },
  {
    'country_code': 'CA',
    'coordinate': '+4901−08816',
    'code': 'America/Nipigon',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+643004−1652423',
    'code': 'America/Nome',
    'status': 'Canonical',
    'utc_offset': '−09:00',
    'utc_dst_offset': '−08:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−0351−03225',
    'code': 'America/Noronha',
    'status': 'Canonical',
    'utc_offset': '−02:00',
    'utc_dst_offset': '−02:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+471551−1014640',
    'code': 'America/North_Dakota/Beulah',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+470659−1011757',
    'code': 'America/North_Dakota/Center',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+465042−1012439',
    'code': 'America/North_Dakota/New_Salem',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'GL',
    'coordinate': '+6411−05144',
    'code': 'America/Nuuk',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−02:00',
  },
  {
    'country_code': 'MX',
    'coordinate': '+2934−10425',
    'code': 'America/Ojinaga',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'PA',
    'coordinate': '+0858−07932',
    'code': 'America/Panama',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+6608−06544',
    'code': 'America/Pangnirtung',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'SR',
    'coordinate': '+0550−05510',
    'code': 'America/Paramaribo',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+332654−1120424',
    'code': 'America/Phoenix',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−07:00',
  },
  {
    'country_code': 'HT',
    'coordinate': '+1832−07220',
    'code': 'America/Port-au-Prince',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'TT',
    'coordinate': '+1039−06131',
    'code': 'America/Port_of_Spain',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−0846−06354',
    'code': 'America/Porto_Velho',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'PR',
    'coordinate': '+182806−0660622',
    'code': 'America/Puerto_Rico',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'CL',
    'coordinate': '−5309−07055',
    'code': 'America/Punta_Arenas',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+4843−09434',
    'code': 'America/Rainy_River',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+624900−0920459',
    'code': 'America/Rankin_Inlet',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−0803−03454',
    'code': 'America/Recife',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+5024−10439',
    'code': 'America/Regina',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+744144−0944945',
    'code': 'America/Resolute',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−0958−06748',
    'code': 'America/Rio_Branco',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−0226−05452',
    'code': 'America/Santarem',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'CL',
    'coordinate': '−3327−07040',
    'code': 'America/Santiago',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'DO',
    'coordinate': '+1828−06954',
    'code': 'America/Santo_Domingo',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'BR',
    'coordinate': '−2332−04637',
    'code': 'America/Sao_Paulo',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
    'active': True,
  },
  {
    'country_code': 'GL',
    'coordinate': '+7029−02158',
    'code': 'America/Scoresbysund',
    'status': 'Canonical',
    'utc_offset': '−01:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+571035−1351807',
    'code': 'America/Sitka',
    'status': 'Canonical',
    'utc_offset': '−09:00',
    'utc_dst_offset': '−08:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+4734−05243',
    'code': 'America/St_Johns',
    'status': 'Canonical',
    'utc_offset': '−03:30',
    'utc_dst_offset': '−02:30',
  },
  {
    'country_code': 'CA',
    'coordinate': '+5017−10750',
    'code': 'America/Swift_Current',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'HN',
    'coordinate': '+1406−08713',
    'code': 'America/Tegucigalpa',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'GL',
    'coordinate': '+7634−06847',
    'code': 'America/Thule',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+4823−08915',
    'code': 'America/Thunder_Bay',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
  },
  {
    'country_code': 'MX',
    'coordinate': '+3232−11701',
    'code': 'America/Tijuana',
    'status': 'Canonical',
    'utc_offset': '−08:00',
    'utc_dst_offset': '−07:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+4339−07923',
    'code': 'America/Toronto',
    'status': 'Canonical',
    'utc_offset': '−05:00',
    'utc_dst_offset': '−04:00',
    'active': True,
  },
  {
    'country_code': 'CA',
    'coordinate': '+4916−12307',
    'code': 'America/Vancouver',
    'status': 'Canonical',
    'utc_offset': '−08:00',
    'utc_dst_offset': '−07:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+6043−13503',
    'code': 'America/Whitehorse',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−07:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+4953−09709',
    'code': 'America/Winnipeg',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+593249−1394338',
    'code': 'America/Yakutat',
    'status': 'Canonical',
    'utc_offset': '−09:00',
    'utc_dst_offset': '−08:00',
  },
  {
    'country_code': 'CA',
    'coordinate': '+6227−11421',
    'code': 'America/Yellowknife',
    'status': 'Canonical',
    'utc_offset': '−07:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'AQ',
    'coordinate': '−6617+11031',
    'code': 'Antarctica/Casey',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'AQ',
    'coordinate': '−6835+07758',
    'code': 'Antarctica/Davis',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'AQ',
    'coordinate': '−6640+14001',
    'code': 'Antarctica/DumontDUrville',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+10:00',
  },
  {
    'country_code': 'AU',
    'coordinate': '−5430+15857',
    'code': 'Antarctica/Macquarie',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'AQ',
    'coordinate': '−6736+06253',
    'code': 'Antarctica/Mawson',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'AQ',
    'coordinate': '−6448−06406',
    'code': 'Antarctica/Palmer',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AQ',
    'coordinate': '−6734−06808',
    'code': 'Antarctica/Rothera',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AQ',
    'coordinate': '−690022+0393524',
    'code': 'Antarctica/Syowa',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'AQ',
    'coordinate': '−720041+0023206',
    'code': 'Antarctica/Troll',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'AQ',
    'coordinate': '−7824+10654',
    'code': 'Antarctica/Vostok',
    'status': 'Canonical',
    'utc_offset': '+06:00',
    'utc_dst_offset': '+06:00',
  },
  {
    'country_code': 'KZ',
    'coordinate': '+4315+07657',
    'code': 'Asia/Almaty',
    'status': 'Canonical',
    'utc_offset': '+06:00',
    'utc_dst_offset': '+06:00',
  },
  {
    'country_code': 'JO',
    'coordinate': '+3157+03556',
    'code': 'Asia/Amman',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+6445+17729',
    'code': 'Asia/Anadyr',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+12:00',
  },
  {
    'country_code': 'KZ',
    'coordinate': '+4431+05016',
    'code': 'Asia/Aqtau',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'KZ',
    'coordinate': '+5017+05710',
    'code': 'Asia/Aqtobe',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'TM',
    'coordinate': '+3757+05823',
    'code': 'Asia/Ashgabat',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'KZ',
    'coordinate': '+4707+05156',
    'code': 'Asia/Atyrau',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'IQ',
    'coordinate': '+3321+04425',
    'code': 'Asia/Baghdad',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'AZ',
    'coordinate': '+4023+04951',
    'code': 'Asia/Baku',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
  },
  {
    'country_code': 'TH',
    'coordinate': '+1345+10031',
    'code': 'Asia/Bangkok',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5322+08345',
    'code': 'Asia/Barnaul',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'LB',
    'coordinate': '+3353+03530',
    'code': 'Asia/Beirut',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'KG',
    'coordinate': '+4254+07436',
    'code': 'Asia/Bishkek',
    'status': 'Canonical',
    'utc_offset': '+06:00',
    'utc_dst_offset': '+06:00',
  },
  {
    'country_code': 'BN',
    'coordinate': '+0456+11455',
    'code': 'Asia/Brunei',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5203+11328',
    'code': 'Asia/Chita',
    'status': 'Canonical',
    'utc_offset': '+09:00',
    'utc_dst_offset': '+09:00',
  },
  {
    'country_code': 'MN',
    'coordinate': '+4804+11430',
    'code': 'Asia/Choibalsan',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'LK',
    'coordinate': '+0656+07951',
    'code': 'Asia/Colombo',
    'status': 'Canonical',
    'utc_offset': '+05:30',
    'utc_dst_offset': '+05:30',
  },
  {
    'country_code': 'SY',
    'coordinate': '+3330+03618',
    'code': 'Asia/Damascus',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'BD',
    'coordinate': '+2343+09025',
    'code': 'Asia/Dhaka',
    'status': 'Canonical',
    'utc_offset': '+06:00',
    'utc_dst_offset': '+06:00',
  },
  {
    'country_code': 'TL',
    'coordinate': '−0833+12535',
    'code': 'Asia/Dili',
    'status': 'Canonical',
    'utc_offset': '+09:00',
    'utc_dst_offset': '+09:00',
  },
  {
    'country_code': 'AE',
    'coordinate': '+2518+05518',
    'code': 'Asia/Dubai',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
    'active': True,
  },
  {
    'country_code': 'TJ',
    'coordinate': '+3835+06848',
    'code': 'Asia/Dushanbe',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'CY',
    'coordinate': '+3507+03357',
    'code': 'Asia/Famagusta',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'PS',
    'coordinate': '+3130+03428',
    'code': 'Asia/Gaza',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'PS',
    'coordinate': '+313200+0350542',
    'code': 'Asia/Hebron',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'VN',
    'coordinate': '+1045+10640',
    'code': 'Asia/Ho_Chi_Minh',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'HK',
    'coordinate': '+2217+11409',
    'code': 'Asia/Hong_Kong',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'MN',
    'coordinate': '+4801+09139',
    'code': 'Asia/Hovd',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5216+10420',
    'code': 'Asia/Irkutsk',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'ID',
    'coordinate': '−0610+10648',
    'code': 'Asia/Jakarta',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'ID',
    'coordinate': '−0232+14042',
    'code': 'Asia/Jayapura',
    'status': 'Canonical',
    'utc_offset': '+09:00',
    'utc_dst_offset': '+09:00',
  },
  {
    'country_code': 'IL',
    'coordinate': '+314650+0351326',
    'code': 'Asia/Jerusalem',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'AF',
    'coordinate': '+3431+06912',
    'code': 'Asia/Kabul',
    'status': 'Canonical',
    'utc_offset': '+04:30',
    'utc_dst_offset': '+04:30',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5301+15839',
    'code': 'Asia/Kamchatka',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+12:00',
  },
  {
    'country_code': 'PK',
    'coordinate': '+2452+06703',
    'code': 'Asia/Karachi',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'NP',
    'coordinate': '+2743+08519',
    'code': 'Asia/Kathmandu',
    'status': 'Canonical',
    'utc_offset': '+05:45',
    'utc_dst_offset': '+05:45',
  },
  {
    'country_code': 'RU',
    'coordinate': '+623923+1353314',
    'code': 'Asia/Khandyga',
    'status': 'Canonical',
    'utc_offset': '+09:00',
    'utc_dst_offset': '+09:00',
  },
  {
    'country_code': 'IN',
    'coordinate': '+2232+08822',
    'code': 'Asia/Kolkata',
    'status': 'Canonical',
    'utc_offset': '+05:30',
    'utc_dst_offset': '+05:30',
    'active': True,
  },
  {
    'country_code': 'RU',
    'coordinate': '+5601+09250',
    'code': 'Asia/Krasnoyarsk',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'MY',
    'coordinate': '+0310+10142',
    'code': 'Asia/Kuala_Lumpur',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'MY',
    'coordinate': '+0133+11020',
    'code': 'Asia/Kuching',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'MO',
    'coordinate': '+221150+1133230',
    'code': 'Asia/Macau',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5934+15048',
    'code': 'Asia/Magadan',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'ID',
    'coordinate': '−0507+11924',
    'code': 'Asia/Makassar',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'PH',
    'coordinate': '+1435+12100',
    'code': 'Asia/Manila',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'CY',
    'coordinate': '+3510+03322',
    'code': 'Asia/Nicosia',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5345+08707',
    'code': 'Asia/Novokuznetsk',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5502+08255',
    'code': 'Asia/Novosibirsk',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5500+07324',
    'code': 'Asia/Omsk',
    'status': 'Canonical',
    'utc_offset': '+06:00',
    'utc_dst_offset': '+06:00',
  },
  {
    'country_code': 'KZ',
    'coordinate': '+5113+05121',
    'code': 'Asia/Oral',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'ID',
    'coordinate': '−0002+10920',
    'code': 'Asia/Pontianak',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'KP',
    'coordinate': '+3901+12545',
    'code': 'Asia/Pyongyang',
    'status': 'Canonical',
    'utc_offset': '+09:00',
    'utc_dst_offset': '+09:00',
  },
  {
    'country_code': 'QA',
    'coordinate': '+2517+05132',
    'code': 'Asia/Qatar',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'KZ',
    'coordinate': '+5312+06337',
    'code': 'Asia/Qostanay',
    'status': 'Canonical',
    'utc_offset': '+06:00',
    'utc_dst_offset': '+06:00',
  },
  {
    'country_code': 'KZ',
    'coordinate': '+4448+06528',
    'code': 'Asia/Qyzylorda',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'SA',
    'coordinate': '+2438+04643',
    'code': 'Asia/Riyadh',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+4658+14242',
    'code': 'Asia/Sakhalin',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'UZ',
    'coordinate': '+3940+06648',
    'code': 'Asia/Samarkand',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'KR',
    'coordinate': '+3733+12658',
    'code': 'Asia/Seoul',
    'status': 'Canonical',
    'utc_offset': '+09:00',
    'utc_dst_offset': '+09:00',
    'active': True,
  },
  {
    'country_code': 'CN',
    'coordinate': '+3114+12128',
    'code': 'Asia/Shanghai',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
    'active': True,
  },
  {
    'country_code': 'SG',
    'coordinate': '+0117+10351',
    'code': 'Asia/Singapore',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
    'active': True,
  },
  {
    'country_code': 'RU',
    'coordinate': '+6728+15343',
    'code': 'Asia/Srednekolymsk',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'TW',
    'coordinate': '+2503+12130',
    'code': 'Asia/Taipei',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'UZ',
    'coordinate': '+4120+06918',
    'code': 'Asia/Tashkent',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'GE',
    'coordinate': '+4143+04449',
    'code': 'Asia/Tbilisi',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
  },
  {
    'country_code': 'IR',
    'coordinate': '+3540+05126',
    'code': 'Asia/Tehran',
    'status': 'Canonical',
    'utc_offset': '+03:30',
    'utc_dst_offset': '+04:30',
  },
  {
    'country_code': 'BT',
    'coordinate': '+2728+08939',
    'code': 'Asia/Thimphu',
    'status': 'Canonical',
    'utc_offset': '+06:00',
    'utc_dst_offset': '+06:00',
  },
  {
    'country_code': 'JP',
    'coordinate': '+353916+1394441',
    'code': 'Asia/Tokyo',
    'status': 'Canonical',
    'utc_offset': '+09:00',
    'utc_dst_offset': '+09:00',
    'active': True,
  },
  {
    'country_code': 'RU',
    'coordinate': '+5630+08458',
    'code': 'Asia/Tomsk',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'MN',
    'coordinate': '+4755+10653',
    'code': 'Asia/Ulaanbaatar',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'CN',
    'coordinate': '+4348+08735',
    'code': 'Asia/Urumqi',
    'status': 'Canonical',
    'utc_offset': '+06:00',
    'utc_dst_offset': '+06:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+643337+1431336',
    'code': 'Asia/Ust-Nera',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+10:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+4310+13156',
    'code': 'Asia/Vladivostok',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+10:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+6200+12940',
    'code': 'Asia/Yakutsk',
    'status': 'Canonical',
    'utc_offset': '+09:00',
    'utc_dst_offset': '+09:00',
  },
  {
    'country_code': 'MM',
    'coordinate': '+1647+09610',
    'code': 'Asia/Yangon',
    'status': 'Canonical',
    'utc_offset': '+06:30',
    'utc_dst_offset': '+06:30',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5651+06036',
    'code': 'Asia/Yekaterinburg',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'AM',
    'coordinate': '+4011+04430',
    'code': 'Asia/Yerevan',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
  },
  {
    'country_code': 'PT',
    'coordinate': '+3744−02540',
    'code': 'Atlantic/Azores',
    'status': 'Canonical',
    'utc_offset': '−01:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'BM',
    'coordinate': '+3217−06446',
    'code': 'Atlantic/Bermuda',
    'status': 'Canonical',
    'utc_offset': '−04:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'ES',
    'coordinate': '+2806−01524',
    'code': 'Atlantic/Canary',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+01:00',
  },
  {
    'country_code': 'CV',
    'coordinate': '+1455−02331',
    'code': 'Atlantic/Cape_Verde',
    'status': 'Canonical',
    'utc_offset': '−01:00',
    'utc_dst_offset': '−01:00',
  },
  {
    'country_code': 'FO',
    'coordinate': '+6201−00646',
    'code': 'Atlantic/Faroe',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+01:00',
  },
  {
    'country_code': 'PT',
    'coordinate': '+3238−01654',
    'code': 'Atlantic/Madeira',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+01:00',
  },
  {
    'country_code': 'IS',
    'coordinate': '+6409−02151',
    'code': 'Atlantic/Reykjavik',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'GS',
    'coordinate': '−5416−03632',
    'code': 'Atlantic/South_Georgia',
    'status': 'Canonical',
    'utc_offset': '−02:00',
    'utc_dst_offset': '−02:00',
  },
  {
    'country_code': 'FK',
    'coordinate': '−5142−05751',
    'code': 'Atlantic/Stanley',
    'status': 'Canonical',
    'utc_offset': '−03:00',
    'utc_dst_offset': '−03:00',
  },
  {
    'country_code': 'AU',
    'coordinate': '−3455+13835',
    'code': 'Australia/Adelaide',
    'status': 'Canonical',
    'utc_offset': '+09:30',
    'utc_dst_offset': '+10:30',
  },
  {
    'country_code': 'AU',
    'coordinate': '−2728+15302',
    'code': 'Australia/Brisbane',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+10:00',
  },
  {
    'country_code': 'AU',
    'coordinate': '−3157+14127',
    'code': 'Australia/Broken_Hill',
    'status': 'Canonical',
    'utc_offset': '+09:30',
    'utc_dst_offset': '+10:30',
  },
  {
    'country_code': 'AU',
    'coordinate': '−1228+13050',
    'code': 'Australia/Darwin',
    'status': 'Canonical',
    'utc_offset': '+09:30',
    'utc_dst_offset': '+09:30',
  },
  {
    'country_code': 'AU',
    'coordinate': '−3143+12852',
    'code': 'Australia/Eucla',
    'status': 'Canonical',
    'utc_offset': '+08:45',
    'utc_dst_offset': '+08:45',
  },
  {
    'country_code': 'AU',
    'coordinate': '−4253+14719',
    'code': 'Australia/Hobart',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'AU',
    'coordinate': '−2016+14900',
    'code': 'Australia/Lindeman',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+10:00',
  },
  {
    'country_code': 'AU',
    'coordinate': '−3133+15905',
    'code': 'Australia/Lord_Howe',
    'status': 'Canonical',
    'utc_offset': '+10:30',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'AU',
    'coordinate': '−3749+14458',
    'code': 'Australia/Melbourne',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'AU',
    'coordinate': '−3157+11551',
    'code': 'Australia/Perth',
    'status': 'Canonical',
    'utc_offset': '+08:00',
    'utc_dst_offset': '+08:00',
  },
  {
    'country_code': 'AU',
    'coordinate': '−3352+15113',
    'code': 'Australia/Sydney',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+11:00',
    'active': True,
  },
  {
    'country_code': 'NL',
    'coordinate': '+5222+00454',
    'code': 'Europe/Amsterdam',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'AD',
    'coordinate': '+4230+00131',
    'code': 'Europe/Andorra',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+4621+04803',
    'code': 'Europe/Astrakhan',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
  },
  {
    'country_code': 'GR',
    'coordinate': '+3758+02343',
    'code': 'Europe/Athens',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'RS',
    'coordinate': '+4450+02030',
    'code': 'Europe/Belgrade',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'DE',
    'coordinate': '+5230+01322',
    'code': 'Europe/Berlin',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
    'active': True,
  },
  {
    'country_code': 'BE',
    'coordinate': '+5050+00420',
    'code': 'Europe/Brussels',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'RO',
    'coordinate': '+4426+02606',
    'code': 'Europe/Bucharest',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'HU',
    'coordinate': '+4730+01905',
    'code': 'Europe/Budapest',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'MD',
    'coordinate': '+4700+02850',
    'code': 'Europe/Chisinau',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'DK',
    'coordinate': '+5540+01235',
    'code': 'Europe/Copenhagen',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'IE',
    'coordinate': '+5320−00615',
    'code': 'Europe/Dublin',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'GI',
    'coordinate': '+3608−00521',
    'code': 'Europe/Gibraltar',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'FI',
    'coordinate': '+6010+02458',
    'code': 'Europe/Helsinki',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'TR',
    'coordinate': '+4101+02858',
    'code': 'Europe/Istanbul',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
    'active': True,
  },
  {
    'country_code': 'RU',
    'coordinate': '+5443+02030',
    'code': 'Europe/Kaliningrad',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'UA',
    'coordinate': '+5026+03031',
    'code': 'Europe/Kiev',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5836+04939',
    'code': 'Europe/Kirov',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'PT',
    'coordinate': '+3843−00908',
    'code': 'Europe/Lisbon',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+01:00',
  },
  {
    'country_code': 'GB',
    'coordinate': '+513030−0000731',
    'code': 'Europe/London',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+01:00',
    'active': True,
  },
  {
    'country_code': 'LU',
    'coordinate': '+4936+00609',
    'code': 'Europe/Luxembourg',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'ES',
    'coordinate': '+4024−00341',
    'code': 'Europe/Madrid',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'MT',
    'coordinate': '+3554+01431',
    'code': 'Europe/Malta',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'BY',
    'coordinate': '+5354+02734',
    'code': 'Europe/Minsk',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'MC',
    'coordinate': '+4342+00723',
    'code': 'Europe/Monaco',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+554521+0373704',
    'code': 'Europe/Moscow',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
    'active': True,
  },
  {
    'country_code': 'NO',
    'coordinate': '+5955+01045',
    'code': 'Europe/Oslo',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'FR',
    'coordinate': '+4852+00220',
    'code': 'Europe/Paris',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
    'active': True,
  },
  {
    'country_code': 'CZ',
    'coordinate': '+5005+01426',
    'code': 'Europe/Prague',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'LV',
    'coordinate': '+5657+02406',
    'code': 'Europe/Riga',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'IT',
    'coordinate': '+4154+01229',
    'code': 'Europe/Rome',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5312+05009',
    'code': 'Europe/Samara',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5134+04602',
    'code': 'Europe/Saratov',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
  },
  {
    'country_code': 'UA',
    'coordinate': '+4457+03406',
    'code': 'Europe/Simferopol',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'BG',
    'coordinate': '+4241+02319',
    'code': 'Europe/Sofia',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'SE',
    'coordinate': '+5920+01803',
    'code': 'Europe/Stockholm',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'EE',
    'coordinate': '+5925+02445',
    'code': 'Europe/Tallinn',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'AL',
    'coordinate': '+4120+01950',
    'code': 'Europe/Tirane',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+5420+04824',
    'code': 'Europe/Ulyanovsk',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
  },
  {
    'country_code': 'UA',
    'coordinate': '+4837+02218',
    'code': 'Europe/Uzhgorod',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'AT',
    'coordinate': '+4813+01620',
    'code': 'Europe/Vienna',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'LT',
    'coordinate': '+5441+02519',
    'code': 'Europe/Vilnius',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'RU',
    'coordinate': '+4844+04425',
    'code': 'Europe/Volgograd',
    'status': 'Canonical',
    'utc_offset': '+03:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'PL',
    'coordinate': '+5215+02100',
    'code': 'Europe/Warsaw',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'UA',
    'coordinate': '+4750+03510',
    'code': 'Europe/Zaporozhye',
    'status': 'Canonical',
    'utc_offset': '+02:00',
    'utc_dst_offset': '+03:00',
  },
  {
    'country_code': 'CH',
    'coordinate': '+4723+00832',
    'code': 'Europe/Zurich',
    'status': 'Canonical',
    'utc_offset': '+01:00',
    'utc_dst_offset': '+02:00',
  },
  {
    'country_code': 'nan',
    'coordinate': 'nan',
    'code': 'Factory',
    'status': 'Canonical',
    'utc_offset': '+00:00',
    'utc_dst_offset': '+00:00',
  },
  {
    'country_code': 'IO',
    'coordinate': '−0720+07225',
    'code': 'Indian/Chagos',
    'status': 'Canonical',
    'utc_offset': '+06:00',
    'utc_dst_offset': '+06:00',
  },
  {
    'country_code': 'CX',
    'coordinate': '−1025+10543',
    'code': 'Indian/Christmas',
    'status': 'Canonical',
    'utc_offset': '+07:00',
    'utc_dst_offset': '+07:00',
  },
  {
    'country_code': 'CC',
    'coordinate': '−1210+09655',
    'code': 'Indian/Cocos',
    'status': 'Canonical',
    'utc_offset': '+06:30',
    'utc_dst_offset': '+06:30',
  },
  {
    'country_code': 'TF',
    'coordinate': '−492110+0701303',
    'code': 'Indian/Kerguelen',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'SC',
    'coordinate': '−0440+05528',
    'code': 'Indian/Mahe',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
  },
  {
    'country_code': 'MV',
    'coordinate': '+0410+07330',
    'code': 'Indian/Maldives',
    'status': 'Canonical',
    'utc_offset': '+05:00',
    'utc_dst_offset': '+05:00',
  },
  {
    'country_code': 'MU',
    'coordinate': '−2010+05730',
    'code': 'Indian/Mauritius',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
  },
  {
    'country_code': 'RE',
    'coordinate': '−2052+05528',
    'code': 'Indian/Reunion',
    'status': 'Canonical',
    'utc_offset': '+04:00',
    'utc_dst_offset': '+04:00',
  },
  {
    'country_code': 'WS',
    'coordinate': '−1350−17144',
    'code': 'Pacific/Apia',
    'status': 'Canonical',
    'utc_offset': '+13:00',
    'utc_dst_offset': '+14:00',
  },
  {
    'country_code': 'NZ',
    'coordinate': '−3652+17446',
    'code': 'Pacific/Auckland',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+13:00',
  },
  {
    'country_code': 'PG',
    'coordinate': '−0613+15534',
    'code': 'Pacific/Bougainville',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'NZ',
    'coordinate': '−4357−17633',
    'code': 'Pacific/Chatham',
    'status': 'Canonical',
    'utc_offset': '+12:45',
    'utc_dst_offset': '+13:45',
  },
  {
    'country_code': 'FM',
    'coordinate': '+0725+15147',
    'code': 'Pacific/Chuuk',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+10:00',
  },
  {
    'country_code': 'CL',
    'coordinate': '−2709−10926',
    'code': 'Pacific/Easter',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−05:00',
  },
  {
    'country_code': 'VU',
    'coordinate': '−1740+16825',
    'code': 'Pacific/Efate',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'KI',
    'coordinate': '−0308−17105',
    'code': 'Pacific/Enderbury',
    'status': 'Canonical',
    'utc_offset': '+13:00',
    'utc_dst_offset': '+13:00',
  },
  {
    'country_code': 'TK',
    'coordinate': '−0922−17114',
    'code': 'Pacific/Fakaofo',
    'status': 'Canonical',
    'utc_offset': '+13:00',
    'utc_dst_offset': '+13:00',
  },
  {
    'country_code': 'FJ',
    'coordinate': '−1808+17825',
    'code': 'Pacific/Fiji',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+13:00',
  },
  {
    'country_code': 'TV',
    'coordinate': '−0831+17913',
    'code': 'Pacific/Funafuti',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+12:00',
  },
  {
    'country_code': 'EC',
    'coordinate': '−0054−08936',
    'code': 'Pacific/Galapagos',
    'status': 'Canonical',
    'utc_offset': '−06:00',
    'utc_dst_offset': '−06:00',
  },
  {
    'country_code': 'PF',
    'coordinate': '−2308−13457',
    'code': 'Pacific/Gambier',
    'status': 'Canonical',
    'utc_offset': '−09:00',
    'utc_dst_offset': '−09:00',
  },
  {
    'country_code': 'SB',
    'coordinate': '−0932+16012',
    'code': 'Pacific/Guadalcanal',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'GU',
    'coordinate': '+1328+14445',
    'code': 'Pacific/Guam',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+10:00',
  },
  {
    'country_code': 'US',
    'coordinate': '+211825−1575130',
    'code': 'Pacific/Honolulu',
    'status': 'Canonical',
    'utc_offset': '−10:00',
    'utc_dst_offset': '−10:00',
  },
  {
    'country_code': 'KI',
    'coordinate': '+0152−15720',
    'code': 'Pacific/Kiritimati',
    'status': 'Canonical',
    'utc_offset': '+14:00',
    'utc_dst_offset': '+14:00',
  },
  {
    'country_code': 'FM',
    'coordinate': '+0519+16259',
    'code': 'Pacific/Kosrae',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'MH',
    'coordinate': '+0905+16720',
    'code': 'Pacific/Kwajalein',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+12:00',
  },
  {
    'country_code': 'MH',
    'coordinate': '+0709+17112',
    'code': 'Pacific/Majuro',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+12:00',
  },
  {
    'country_code': 'PF',
    'coordinate': '−0900−13930',
    'code': 'Pacific/Marquesas',
    'status': 'Canonical',
    'utc_offset': '−09:30',
    'utc_dst_offset': '−09:30',
  },
  {
    'country_code': 'NR',
    'coordinate': '−0031+16655',
    'code': 'Pacific/Nauru',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+12:00',
  },
  {
    'country_code': 'NU',
    'coordinate': '−1901−16955',
    'code': 'Pacific/Niue',
    'status': 'Canonical',
    'utc_offset': '−11:00',
    'utc_dst_offset': '−11:00',
  },
  {
    'country_code': 'NF',
    'coordinate': '−2903+16758',
    'code': 'Pacific/Norfolk',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+12:00',
  },
  {
    'country_code': 'NC',
    'coordinate': '−2216+16627',
    'code': 'Pacific/Noumea',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'AS',
    'coordinate': '−1416−17042',
    'code': 'Pacific/Pago_Pago',
    'status': 'Canonical',
    'utc_offset': '−11:00',
    'utc_dst_offset': '−11:00',
  },
  {
    'country_code': 'PW',
    'coordinate': '+0720+13429',
    'code': 'Pacific/Palau',
    'status': 'Canonical',
    'utc_offset': '+09:00',
    'utc_dst_offset': '+09:00',
  },
  {
    'country_code': 'PN',
    'coordinate': '−2504−13005',
    'code': 'Pacific/Pitcairn',
    'status': 'Canonical',
    'utc_offset': '−08:00',
    'utc_dst_offset': '−08:00',
  },
  {
    'country_code': 'FM',
    'coordinate': '+0658+15813',
    'code': 'Pacific/Pohnpei',
    'status': 'Canonical',
    'utc_offset': '+11:00',
    'utc_dst_offset': '+11:00',
  },
  {
    'country_code': 'PG',
    'coordinate': '−0930+14710',
    'code': 'Pacific/Port_Moresby',
    'status': 'Canonical',
    'utc_offset': '+10:00',
    'utc_dst_offset': '+10:00',
  },
  {
    'country_code': 'CK',
    'coordinate': '−2114−15946',
    'code': 'Pacific/Rarotonga',
    'status': 'Canonical',
    'utc_offset': '−10:00',
    'utc_dst_offset': '−10:00',
  },
  {
    'country_code': 'PF',
    'coordinate': '−1732−14934',
    'code': 'Pacific/Tahiti',
    'status': 'Canonical',
    'utc_offset': '−10:00',
    'utc_dst_offset': '−10:00',
  },
  {
    'country_code': 'KI',
    'coordinate': '+0125+17300',
    'code': 'Pacific/Tarawa',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+12:00',
  },
  {
    'country_code': 'TO',
    'coordinate': '−2110−17510',
    'code': 'Pacific/Tongatapu',
    'status': 'Canonical',
    'utc_offset': '+13:00',
    'utc_dst_offset': '+13:00',
  },
  {
    'country_code': 'UM',
    'coordinate': '+1917+16637',
    'code': 'Pacific/Wake',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+12:00',
  },
  {
    'country_code': 'WF',
    'coordinate': '−1318−17610',
    'code': 'Pacific/Wallis',
    'status': 'Canonical',
    'utc_offset': '+12:00',
    'utc_dst_offset': '+12:00',
  },
)

TIMEZONE_CODES = tuple(val['code'] for val in CANONICAL)

APP_TIMEZONES = tuple(val for val in CANONICAL if val.get('active', False))

APP_TIMEZONE_CODES = tuple(
  val['code'] for val in CANONICAL if val.get('active', False)
)

APP_TIMEZONE_CODE_CHOICES = tuple((code, code) for code in APP_TIMEZONE_CODES)
