URLPATTERN_NAMES = (
  'agent_chats',
  'agent_chat_message',
  'agent_chat_messages',
  'agent_job',
  'agent_job_cancel',
  'current_tenant_user',
  'current_user',
  'current_user_email',
  'current_user_image',
  'current_user_languages',
  'current_user_language',
  'current_user_links',
  'current_user_link',
  'current_user_password',
  'current_user_tenant_invitation_code_accept',
  'current_user_tenant_invitation_code_decline',
  'current_user_tenant_invitation_codes',
  'current_user_tenants',
  'email_availability',
  'email_verification',
  'email_verification_code_email',
  'new_tenant',
  'new_user',
  'password_reset',
  'password_reset_code',
  'password_reset_code_email',
  'shares',
  'sso_authorization_url',
  'sso_enablement_status',
  'tenant',
  'tenant_invitation_code',
  'tenant_invitation_codes',
  'tenant_invitation_code_email',
  'tenant_invitation_code_tenant',
  'tenant_users',
  'tenant_user',
  'tenant_user_autocomplete',
  'tenant_user_role',
  'token_pair',
  'token_refresh',
  'token_revoke',
)

API_TAGS = [
  {
    'name': 'auth',
    'description': 'Authentication endpoints for token issuance, token lifecycle, email verification, and password reset flows.',
    'class_names': [
      'EmailAvailabilityView',
      'EmailVerificationCodeEmailView',
      'EmailVerificationCodeView',
      'PasswordResetCodeEmailView',
      'PasswordResetCodeView',
      'PasswordResetView',
      'TokenPairView',
      'TokenRefreshView',
      'TokenRevokeView',
    ],
  },
  {
    'name': 'sso',
    'description': 'Single sign-on endpoints for determining SSO availability and creating authorization URLs.',
    'class_names': [
      'SsoAuthorizationUrlView',
      'SsoEnablementStatusView',
    ],
  },
  {
    'name': 'users',
    'description': 'Endpoints for current-user profile, registration, password, language, and link management.',
    'class_names': [
      'CurrentUserEmailView',
      'CurrentUserImageView',
      'CurrentUserLanguageListView',
      'CurrentUserLanguageView',
      'CurrentUserLinkListView',
      'CurrentUserLinkView',
      'CurrentUserPasswordView',
      'CurrentUserView',
      'NewUserView',
    ],
  },
  {
    'name': 'tenants',
    'description': 'Endpoints for tenant creation, retrieval, update, and listing the current user tenant memberships.',
    'class_names': [
      'CurrentUserTenantListView',
      'NewTenantView',
      'TenantView',
    ],
  },
  {
    'name': 'tenant_users',
    'description': 'Endpoints for managing tenant membership records, roles, and tenant-scoped user lookups.',
    'class_names': [
      'CurrentTenantUserView',
      'TenantUserAutocompleteView',
      'TenantUserListView',
      'TenantUserRoleView',
      'TenantUserView',
    ],
  },
  {
    'name': 'tenant_invitations',
    'description': 'Endpoints for issuing tenant invitations, checking invitation availability, and accepting or declining invitations.',
    'class_names': [
      'CurrentUserTenantInvitationCodeAcceptView',
      'CurrentUserTenantInvitationCodeDeclineView',
      'CurrentUserTenantInvitationCodeListView',
      'TenantInvitationCodeEmailView',
      'TenantInvitationCodeListView',
      'TenantInvitationCodeTenantView',
      'TenantInvitationCodeView',
    ],
  },
  {
    'name': 'agent',
    'description': 'Tenant-scoped AI assistant endpoints for chats, chat messages, and long-running agent jobs.',
    'class_names': [
      'TenantScopedAgentChatListView',
      'TenantScopedAgentChatMessageListView',
      'TenantScopedAgentChatMessageView',
      'TenantScopedAgentJobCancelView',
      'TenantScopedAgentJobView',
    ],
  },
  {
    'name': 'system',
    'description': 'Endpoints for internal shared application parameters used by the client.',
    'class_names': [
      'ShareView',
    ],
  },
]
